# Generated by Django 5.0.7 on 2024-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='needsUpdate',
            field=models.BooleanField(default=False),
        ),
    ]
