# Generated by Django 5.0.7 on 2024-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0002_submission_needsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='needsUpdate',
            field=models.BooleanField(default=True),
        ),
    ]
