# Generated by Django 5.0.7 on 2024-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_app', '0003_submission_slug_alter_submission_needsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_solved', models.IntegerField()),
                ('easy_solved', models.IntegerField()),
                ('medium_solved', models.IntegerField()),
                ('hard_solved', models.IntegerField()),
            ],
        ),
    ]
