# Generated by Django 5.0.7 on 2024-08-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('custom_class', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
                ('skill_proof', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='')),
                ('related_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devchris.skill')),
            ],
        ),
    ]
