# Generated by Django 5.0.7 on 2024-08-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0004_alter_content_img_alter_project_img_alter_skill_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_proof',
        ),
    ]
