# Generated by Django 5.0.7 on 2024-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0007_alter_skill_options_remove_project_related_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_skill',
            field=models.ManyToManyField(blank=True, to='devchris.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='title', max_length=300),
        ),
    ]
