# Generated by Django 5.0.7 on 2024-08-08 07:26

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0008_alter_project_related_skill_alter_skill_title'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='test_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_covers', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
