# Generated by Django 5.0.7 on 2024-08-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0013_remove_skill_test_img_alter_skill_img'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='skill',
        #     name='test_img',
        # ),
    ]
