# Generated by Django 5.0.7 on 2024-08-08 08:25

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0015_remove_skill_img_remove_skill_test_img'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_img', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
