# Generated by Django 5.0.7 on 2024-08-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0016_skill_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillproof',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='devchris.skill'),
        ),
    ]
