# Generated by Django 5.0.7 on 2024-08-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris', '0019_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.TextField(blank=True, max_length=150, unique=True),
        ),
    ]
