# Generated by Django 5.0.7 on 2024-08-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project Title', max_length=300),
        ),
        migrations.AlterField(
            model_name='content',
            name='custom_class',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/% Y/% m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='static/images/% Y/% m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devchris_app.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(upload_to='static/images/% Y/% m/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_proof',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
