# Generated by Django 5.0.7 on 2024-08-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0002_project_title_alter_content_custom_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devchris_app.skill')),
            ],
        ),
    ]
