# Generated by Django 5.0.7 on 2024-08-02 17:39

import devchris_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0003_skillproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=devchris_app.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to=devchris_app.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=models.ImageField(upload_to=devchris_app.models.get_upload_path),
        ),
    ]
