# Generated by Django 5.0.7 on 2024-08-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0005_remove_skill_skill_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_title',
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='title', max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='title', max_length=300),
        ),
    ]
