# Generated by Django 5.0.7 on 2024-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0006_remove_skill_skill_title_content_title_skill_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_skill',
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='title', max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='related_skill',
            field=models.ManyToManyField(blank=True, null=True, to='devchris_app.skill'),
        ),
    ]
