# Generated by Django 5.0.7 on 2024-08-08 08:18

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0012_remove_skill_test_img'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='skill',
        #     name='test_img',
        # ),
        migrations.AlterField(
            model_name='skill',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_img', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
