# Generated by Django 5.0.7 on 2024-08-19 13:36

import devchris_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0017_alter_skillproof_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            bases=(models.Model, devchris_app.models.titleMixinClass),
        ),
    ]
