# Generated by Django 5.0.7 on 2024-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0024_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='wyzywig_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
