# Generated by Django 5.0.7 on 2024-08-20 12:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0025_content_wyzywig_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='wyzywig_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
