# Generated by Django 5.0.7 on 2024-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0026_alter_content_wyzywig_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
