# Generated by Django 5.0.7 on 2024-09-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devchris_app', '0027_content_published_project_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='published',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='published',
            new_name='is_published',
        ),
    ]
